import React from 'react';
import { Brain, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-navy-950 border-t border-navy-800 text-slate-400 text-xs py-8 mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        
        {/* Top Disclaimer Banner */}
        <div className="p-4 rounded-lg bg-navy-900/90 border border-blue-900/50 flex items-start gap-3">
          <ShieldAlert className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
          <p className="leading-relaxed text-slate-300">
            <strong className="text-white">RESEARCH & EDUCATIONAL DISCLAIMER:</strong> NeuroScan AI provides AI-assisted image analysis for research support and educational purposes only. Results generated by the system are not a clinical medical diagnosis and must not replace evaluation by a qualified healthcare professional.
          </p>
        </div>

        {/* Footer Navigation & Copyright */}
        <div className="flex flex-col md:flex-row items-center justify-between gap-4 pt-4 border-t border-navy-900">
          <div className="flex items-center gap-2">
            <Brain className="w-4 h-4 text-blue-400" />
            <span className="font-bold text-slate-200">NeuroScan AI</span>
            <span className="text-slate-500">| © 2026 AI-Powered Brain MRI Analysis Platform</span>
          </div>

          <div className="flex items-center space-x-6 text-slate-400">
            <Link to="/about" className="hover:text-slate-200 transition-colors">About</Link>
            <Link to="/models" className="hover:text-slate-200 transition-colors">AI Models</Link>
            <Link to="/documentation" className="hover:text-slate-200 transition-colors">Documentation</Link>
            <Link to="/contact" className="hover:text-slate-200 transition-colors">Contact</Link>
          </div>
        </div>

      </div>
    </footer>
  );
};
