import React from 'react';
import { Navbar } from '../components/common/Navbar';
import { Footer } from '../components/common/Footer';
import { BookOpen, ShieldAlert, Cpu, Layers, Eye, FileText, Lock, Activity } from 'lucide-react';

export const DocumentationPage: React.FC = () => {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
      <Navbar />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">
        
        <div className="border-b border-slate-200 pb-4 space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-200 text-blue-700 text-xs font-mono font-medium">
            <BookOpen className="w-3.5 h-3.5" /> SYSTEM DOCUMENTATION & RESEARCH MANUAL
          </div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight font-sans">
            NeuroScan AI Platform Documentation
          </h1>
          <p className="text-xs text-slate-500 font-mono">
            Comprehensive guide to PyTorch model pipelines, image uploads, Grad-CAM, and reporting.
          </p>
        </div>

        {/* Mandatory Research Disclaimer Box */}
        <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 text-xs space-y-2">
          <div className="flex items-center gap-2 font-bold text-amber-800">
            <ShieldAlert className="w-4 h-4 text-amber-600" /> Mandatory Clinical Disclaimer
          </div>
          <p className="leading-relaxed">
            NeuroScan AI provides AI-assisted image analysis for research and educational purposes only. Results generated by this platform do not constitute a standalone medical diagnostic diagnosis and should not replace evaluation by a qualified healthcare professional.
          </p>
        </div>

        {/* Section 1: Getting Started */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Activity className="w-5 h-5 text-blue-600" /> 1. Getting Started
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            To use the MRI prediction engine, register an account or sign in with your research credentials. Unauthenticated requests to prediction APIs are securely protected via standard OAuth2 JWT bearer authentication headers.
          </p>
        </section>

        {/* Section 2: Uploading MRI Images */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-600" /> 2. Uploading MRI Images
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            NeuroScan AI accepts standard medical image formats:
          </p>
          <ul className="list-disc list-inside text-xs text-slate-600 space-y-1 font-mono pl-2">
            <li>JPEG / JPG (.jpg, .jpeg)</li>
            <li>PNG (.png)</li>
            <li>DICOM (.dcm, .dicom) with automatic pixel windowing normalization</li>
          </ul>
          <p className="text-xs text-slate-500 font-mono">Maximum file upload size is set to 10 MB per MRI slice image.</p>
        </section>

        {/* Section 3: Understanding Classification */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Cpu className="w-5 h-5 text-blue-600" /> 3. Understanding Tumor Classification
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            The classification pipeline evaluates input MRI tensors against a 4-class neural network architecture: <strong>Glioma</strong>, <strong>Meningioma</strong>, <strong>Pituitary</strong>, or <strong>No Tumor</strong>. Softmax activation generates a relative probability distribution for each category.
          </p>
        </section>

        {/* Section 4: Understanding Segmentation */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Layers className="w-5 h-5 text-cyan-600" /> 4. Spatial U-Net Tumor Segmentation
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            The U-Net model predicts a binary lesion mask isolating abnormal tissue boundaries. Output telemetry includes total non-zero tumor surface pixels and relative spatial percentage of the total brain slice image.
          </p>
        </section>

        {/* Section 5: Understanding Grad-CAM */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Eye className="w-5 h-5 text-indigo-600" /> 5. Grad-CAM Explainability
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            Gradient-weighted Class Activation Mapping (Grad-CAM) calculates feature map activations at the target convolutional layer during backward propagation to generate intuitive heatmaps overlaying the original scan.
          </p>
        </section>

        {/* Section 6: Privacy & Security */}
        <section className="bg-white p-6 rounded-xl border border-slate-200 space-y-3 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Lock className="w-5 h-5 text-emerald-600" /> 6. Privacy & Security
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            Uploaded images are stored on secure filesystem paths using unique UUIDs. Passwords are key-stretched with bcrypt algorithms. Database queries use parameterized SQLAlchemy ORM to prevent SQL injection vulnerabilities.
          </p>
        </section>

      </main>

      <Footer />
    </div>
  );
};
